<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        
        // \App\Models\User::factory(10)->create();;
        DB::statement("SET foreign_key_checks=0");
        DB::table('users')->truncate();
        DB::table('roles')->truncate();
        DB::table('roles_permission')->truncate();
        DB::table('crud_guard')->truncate();
        DB::statement("SET foreign_key_checks=1");

        DB::table('users')->insertGetId([
            'firstname' => 'admin',
            'lastname' => 'web',
            'email'=>'admin@email.com',
            'password'=>Hash::make('admin')
        ]);



        $collection = array(
            'Admininstrator' => array(
                "login"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "administrator page"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "dashboard" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "cso2 indicator" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "assessment" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "finance" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "cso profile"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "project tracking document"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "lms Data"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                )
            ),
            'CSO2 PMO-Finance' => array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "assessment" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "finance" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "cso profile"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "lms Data"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                )
            ),
            'CSO2 PMO-COP' => array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "assessment" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "finance" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso profile"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>true,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "lms Data"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                )
            ),
            'CSO2 PMO-MEAL and Partnership' => array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "assessment" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "finance" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso profile"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "lms Data"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                )
            ),
            'CSO2 PMO-Partner'=> array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "assessment" => array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "finance" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso profile"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "lms Data"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                )
            ),
            'CSO2 PMO-Comms and PA'=> array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "assessment" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "finance" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso profile"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "lms Data"=>array(
                    'create'=>true,
                    'read'=>true,
                    'update'=>true,
                    'delete'=>true,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                )
            ),
            'Local Resource Organization'=> array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "assessment" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "finance" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "cso profile"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "lms Data"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>true,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                )
            ),
            'USAID and SCP'=>array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "assessment" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>true,
                ),
                "finance" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "cso profile"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                ),
                "lms Data"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>true,
                    'download'=>true,
                    'print'=>true,
                    'upload'=>false,
                )
            ),
            'Public'=>array(
                "login"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>true,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "administrator page"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "dashboard" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "cso2 indicator" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "assessment" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "finance" => array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "cso profile"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "project tracking document"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                ),
                "lms Data"=>array(
                    'create'=>false,
                    'read'=>false,
                    'update'=>false,
                    'delete'=>false,
                    'view'=>false,
                    'export'=>false,
                    'download'=>false,
                    'print'=>false,
                    'upload'=>false,
                )
            ),
        );

        foreach ( $collection  as $role => $roles_permission){
            $roles_id = DB::table('roles')->insertGetId([
                'name' => $role,
                'guard_name' => 'web',
            ]);
            foreach ($roles_permission as $module => $crude_guard ){
                $roles_permission_id = DB::table('roles_permission')->insertGetId([
                    'module' => $module,
                    'roles_id' => $roles_id,
                ]);
                $crude_guard = DB::table('crud_guard')->insertGetId([
                    'roles_permission_id' => $roles_permission_id,
                    'create' => $crude_guard['upload'],
                    'read' => $crude_guard['upload'],
                    'update' => $crude_guard['upload'],
                    'delete'=> $crude_guard['upload'],
                    'view' => $crude_guard['upload'],
                    'export' =>$crude_guard['upload'],
                    'download' => $crude_guard['upload'],
                    'print' => $crude_guard['upload'],
                    'upload' => $crude_guard['upload'],
                ]);
                var_dump($crude_guard);
            }
            DB::table('users')->insertGetId([
                'firstname' =>  $role,
                'lastname' => 'web',
                'email'=>  $role . '@email.com',
                'password'=>Hash::make( $role)
            ]);
            
        }




        // $multiplied = $collection->map(function ($item, $key) {
        //     // DB::table('roles')->insert([
        //     //     'name' => $item,
        //     //     'guard_name' => 'web',
        //     // ]);
        //     var_dump($item);
        // });

    }

   

   
}
